---
title: "Untitled"
author: "Udochi"
date: "February 27, 2018"
output:
  word_document: default
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
library(foreign)
library(printr)
```
#3**convert table 4 to table 6** 
```{r echo=FALSE,include= TRUE,results='asis'}
pew <- read.spss("pew.sav", to.data.frame=TRUE,stringsAsFactors=FALSE)
pew1 <- pew[c("q16", "reltrad", "income")]
pew1$reltrad <- as.character(pew1$reltrad)
pew1$reltrad <- str_replace(pew1$reltrad, " Churches", "")
pew1$reltrad <- str_replace(pew1$reltrad, " Protestant", " Prot")
pew1$reltrad[pew1$q16 == " Atheist (do not believe in God) "] <- "Atheist"
pew1$reltrad[pew1$q16 == " Agnostic (not sure if there is a God) "] <- "Agnostic"
pew1$reltrad <- str_trim(pew1$reltrad)
pew1$reltrad <- str_replace_all(pew1$reltrad, " \\(.*?\\)", "")

pew1$income <- c("Less than $10,000" = "<$10k", 
                     "10 to under $20,000" = "$10-20k", 
                     "20 to under $30,000" = "$20-30k", 
                     "30 to under $40,000" = "$30-40k", 
                     "40 to under $50,000" = "$40-50k", 
                     "50 to under $75,000" = "$50-75k",
                     "75 to under $100,000" = "$75-100k", 
                     "100 to under $150,000" = "$100-150k", 
                     "$150,000 or more" = ">150k", 
                     "Don't know/Refused (VOL)" = "Don't know/refused")[pew1$income]

pew1$income <- factor(pew1$income, levels = c("<$10k", "$10-20k", "$20-30k", "$30-40k", "$40-50k", "$50-75k", 
                                                      "$75-100k", "$100-150k", ">150k", "Don't know/refused"))

pewfin <- pew1 %>% group_by(reltrad, income) %>% summarize(count = n())

pewfin <- as.data.frame(pewfin)
head(pewfin,10)
```

#**4.convert table 7 to table 8**
```{r echo=FALSE,Include=TRUE,results='asis'}
bb <-read_csv("billboard.csv")
bb.1 <- bb%>% gather(key="week", value ="rank", -year, -artist.inverted, -track, -time, -genre, -date.entered, -date.peaked)%>% 
select(year, artist=artist.inverted, time, track, date=date.entered, week, rank)%>% 
arrange(track)%>% 
filter(!is.na(rank))%>% 
separate(week, into=c("A", "week", "C"), sep=c(1, -8), convert=TRUE)%>% 
select(-A, -C)%>% 
filter(!is.na(week))%>% 
arrange(artist, track)%>% 
mutate(date = date+(week-1)*7)%>% 
mutate(rank = as.numeric(rank))
bb.2 <- as.data.frame(bb.1)
head(bb.2,10)

```
